display_name: out

info: true

build: crystal build --warnings all --stats ./src/out.cr -o bin/out

run: ./bin/out

run_args:

watch:
  - ./src/out.cr
  - ./src/endpoints/**/*.cr
  - ./src/views/**/*.cr
  - ./src/helpers/**/*.cr