display_name: jobs

info: true

build: crystal build --warnings all --stats ./src/jobs.cr -o bin/jobs

run: ./bin/jobs

run_args:

watch:
  - ./src/jobs.cr
  - ./src/jobs/*.cr
  - ./src/jobs/**/*.cr
  - ./src/helpers/**/*.cr