FROM crystallang/crystal:0.29.0

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update -qq && apt-get install -y --no-install-recommends libpq-dev libreadline-dev curl

WORKDIR /usr/src/app/out/

COPY . .

RUN make init.dev